---
name: Test Action
run-name: Test
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:

  Build:
    runs-on: ubuntu-latest
    name: Build and deploy
    container:
      image: docker.io/chapvic/actions:alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
            echo "$GITHUB_CONTEXT"
            echo "$JOB_CONTEXT"

      - name: Get Meta
        id: meta
        run: |
          echo JOB_URL="https://api.github.com/repos/${{github.repository}}/actions/runs/${{ github.run_id }}/jobs" | tee -a $GITHUB_OUTPUT
          echo JOB_ID=$(curl -s -H "Authorization: token ${{env.GITHUB_TOKEN}}" "https://api.github.com/repos/${{github.repository}}/actions/runs/${{github.run_id}}/jobs" | yq -r '.jobs[] | .id') | tee -a $GITHUB_OUTPUT
          echo JOB_ID_URL="${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})/job" | tee -a $GITHUB_OUTPUT

      - name: Send notification
        uses: chapvic/telegram-notify@v1.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          status: ${{ job.status }}
          title: "Test build"
          header: >
            ```
            ${{ github.event.head_commit.message }}
            Run number = ${{ github.run_number }}
            URL = ${{ steps.meta.outputs.JOB_ID_URL }}/${{ steps.meta.outputs.JOB_ID }}
            ```            
#          footer: >
#            [Открыть журнал сборки](${{steps.meta.outputs.JOB_ID_URL}}/${{steps.meta.outputs.JOB_ID}})

      - name: Print Environment
        run: |
          echo "${{ toJson(env) }}"
          echo "${{ toJson(steps) }}"
